User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Info
PidFile "/tmp/tinyproxy.pid"
MaxClients 100
StartServers 2
MinSpareServers 1
MaxSpareServers 4
Allow 0.0.0.0/0
DisableViaHeader Yes
